topology: add numa distances
jaypipes/ghw pull request #204
Opened 2020-12-18 10:53 UTC by fromanirh

Report distances between NUMA nodes as reported by sysfs.

This PR depends on https://github.com/jaypipes/ghw/pull/203 (whose commits are also added here to make the PR compilable) and also serves to demonstrate how to consume the snapshots programmatically, a feature added in https://github.com/jaypipes/ghw/pull/202.

With https://github.com/jaypipes/ghw/pull/203 merged, only https://github.com/jaypipes/ghw/commit/a2f2485401627ee302e8d846f1e75aa2d326db80 is relevant for this PR.

2020-12-18 14:01 UTC, jaypipes requested changes
Hi again @fromanirh, thank you so much for this! I'm really digging this new code.

I actually have only requested thing for you to fix up, which would be to add a line to the README docs for the `ghw.TopologyNode` struct:

https://github.com/jaypipes/ghw#topology

with a description of the new `Distances` field please.

Extra credit for a future PR might be to add to the example code in the README doc section above that shows the user how to, say, list the TopologyNodes "closest" to a particular node.

Other than that, this is awesomesauce.

Best,
-jay

2021-01-06 09:12 UTC, fromanirh commented on pkg/topology/topology_linux.go
> +	items := strings.Split(strings.TrimSpace(string(data)), distanceSeparator)
indeed, very cool! done

2021-01-06 09:18 UTC, fromanirh commented
Updated as requested. The extra credit is a very nice idea, will work on that direction.

2021-01-06 15:36 UTC, jaypipes approved these changes
:+1: awesome work again, @fromanirh!

2021-01-06 15:36 UTC, merged